# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - docker:dind

# The variables below are used when using EBRD Runner!
#variables:
  #http_proxy: "http://ldn3log1.ebrd.com:8888"
  #https_proxy: "http://ldn3log1.ebrd.com:8888"
  #no_proxy: "ldn1cvs2.ebrd.com,localhost,docker,docker:2375"
  ##DOCKER_HOST: tcp://docker:2375/
  #DOCKER_DRIVER: overlay2

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

update-prod:
  stage: build
  script:
    - export TODAY=`date -I`
    - docker build --pull -t "$CI_REGISTRY_IMAGE:${TODAY}" .
    - docker push "$CI_REGISTRY_IMAGE:${TODAY}"
    - docker tag "${CI_REGISTRY_IMAGE}:${TODAY}" "${CI_REGISTRY_IMAGE}"
    - docker tag "${CI_REGISTRY_IMAGE}"
  only:
    - master

test-build:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master
