image: docker:latest

services:
  - docker:dind

variables:
  #DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

before_script:
   - make login

update-prod:
  stage: build
  script:
    - make prod
  only:
    - master

test-build:
  stage: build
  script:
    - make upgrade Dockerfile 
    - make test-build
  except:
    - master
